import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import AuthProvider from "./components/AuthProvider";
import { Session } from "next-auth";

export const metadata: Metadata = {
  title: "Esg",
  description: "Generated by create next app",
};

interface Props {
  session: Session | null
  children: React.ReactNode
}

export default function RootLayout({children, session}: Props) {
  return (
    <html lang="en">
      <body>
        <AuthProvider session={session}>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}